### ISSUE TITLE
Send location STRING to DB

### ISSUE THREAD

**Issue by jwareing** [OrgulousArtichoke/vacaypay#60]

**Comment by valgaze** [comment]
Add to schema:
1) locationString: String,
2) expenseString: "25 currencyType",

Add to expenseFactory .js
function addExpense (expense, stakeholders, callback) {}
1) locationString: String,
2) expenseString: "25 currencyType",

Add to createExpense.js
$scope.expense.locationString
$scope.expense.expenseString

**Comment by valgaze** [comment]
In createExpense.js: change line 38         $http.get('https://maps.googleapis.com/maps/api/geocode/json?address=' + $scope.expense.location)

$scope.expense.locationString
